# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ElegantCamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  
  pod 'Masonry', '~> 1.1.0'
  pod 'SDWebImage'#,'~>3.8.2'
  pod 'SDWebImage/WebP'
  pod 'YYKit', '~> 1.0.9'
#  pod 'GPUImage'
  pod 'CocoaLumberjack'
  pod "ReactiveCocoa", "~> 2.5"
  pod "Shimmer"
  #  pod 'TZImagePickerController', '~> 3.2.7'
  pod 'TZImagePickerController'
  pod 'MMKV', '~> 1.0.23'
  pod 'LBXScan/LBXNative','~> 2.4'
  
  pod 'CLImageEditor', '~> 0.2.4'
#  pod 'MLeaksFinder', '~> 1.0.0'
#  pod 'ZMJImageEditor'
  
  pod "Shimmer"
  pod "WSProgressHUD"
  
  pod 'LookinServer', :configurations => ['Debug']
  pod 'OCMock', :configurations => ['Debug']
  
  target 'ElegantCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'ElegantCameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
